### ISSUE TITLE
Unlicensed files

### ISSUE THREAD

**Issue by anthonypuppo** [jherskovic/MedRec#6]
Can this script be used with the no license required files from https://www.nlm.nih.gov/research/umls/rxnorm/docs/rxnormfiles.html?

**Comment by jherskovic** [comment]
I haven't tested this, but you should be able to. You will have to modify `generate_rxnorm_files.py` because it assumes that the filenames are from the full UMLS distribution (i.e. `MRCONSO.RRF` instead of `RXNCONSO.RRF` in the unlicensed RxNorm files)

**Comment by anthonypuppo** [comment]
As far as I can tell, there’s only one pertinent difference to your algorithm between the Metathesaurus data and the unlicensed RxNorm files: 

From https://www.nlm.nih.gov/research/umls/rxnorm/docs/2017/rxnorm_doco_full_2017-1.html
RXNCONSO.RRF: 
TS 	Term status (no value provided)

I think this is what's causing the generate_rxnorm_file.py script to build 0 concepts and relations.

**Comment by jherskovic** [comment]
Haven't done this in a while... let me take a closer look

**Comment by jherskovic** [comment]
The other problem is that there's no RXNSTY, so there's no semantic type information, which I actually use. So I guess you'll need the full UMLS. Sorry.

**Comment by anthonypuppo** [comment]
Thanks for catching that, I'll grab the full download.
